<?xml version="1.0"?>
<!DOCTYPE bibliography [
<!ELEMENT bibliography (book+)>
<!ELEMENT book (title, author*, publisher?, year?, section*)>
<!ATTLIST book ISBN ID #REQUIRED>
<!ATTLIST book price CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT content (#PCDATA|i)*>
<!ELEMENT section (title, content?, section*)>
]>

<bibliography>
    <book ISBN="A1234" price="400">
        <title>Home Alone</title>
        <author>GR Rohith</author>
        <publisher>Hemananda</publisher>
        <year>2022</year>
        <section>
            <title>Home Alone</title>
            <content>
                <i>Drama</i>
                <i>Fun</i>
                <i>Family</i>
            </content>
        </section>
    </book>
    <book ISBN="B123456" price="10000">
        <title>Beast</title>
        <author>Nelson Dilipkumar</author>
        <publisher>Sun Pictures</publisher>
        <year>2022</year>
        <section>
            <title>Beast</title>
            <content>
                <i>Action</i>
                <i>Drama</i>
                <i>dark Comedy</i>
            </content>
        </section>
    </book>
</bibliography>